# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BusRoutes' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'


end
